### PR TITLE
Add support for batch_id parameter

### PR DESCRIPTION
**Pull request by spib**
See
https://sendgrid.com/docs/API_Reference/Web_API_v3/cancel_schedule_send.html

### CODE REVIEW

**Comment by spib** [comment]
Any idea when this might get merged? I know there's a new library being worked on but this has been waiting to be merged for two months now

**Comment by thinkingserious** [comment]
Hello @spib,

Thanks for the pull request!

For us to merge this, we'll need a signed CLA: https://github.com/sendgrid/smtpapi-csharp/blob/master/CONTRIBUTING.md#cla

Once you've completed that step, we'll be happy to review for merging.

With Best Regards,

Elmer

**Comment by spib** [comment]
The CLA requirement is too high a barrier to entry so I'll just withdraw this request, thanks anyway. Maybe you should consider a more automated license agreement process which doesn't put the onus on the submitter

**Comment by thinkingserious** [comment]
Hello @spib,

Thanks for the feedback and I feel your pain! I've had to recently submit a faxed CLA :/

We do have plans to automate this process, but that wont likely happen until later this year. However, your voice is heard and help us to prioritize this.

If you have any additional feedback, we would be happy to consider it.

With Best Regards,

Elmer

BTW, Batch ID is now included in the new v3 /mail/send endpoint: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html which is supported by our new library: https://github.com/sendgrid/sendgrid-csharp/tree/v3beta (coming out of beta in a few weeks)

Cheers!

**Pull request closed without merging**
