### PR TITLE
Code Cleanup and escaping foreign encoding support

### LINKED ISSUE #4: JSON values should be escaped
Since the SendGrid API requires UTF-8 values to be escaped in the JSON structures, this should be handled by Utils.cs. Possibly by using JSON.NET and proper serialization settings.

### PR DESCRIPTION
**Pull request by 0xdeafcafe**
This should fix #4. Could you take a look at it @elbuo8?

### CODE REVIEW

**Comment by VictorAcatrinei** [comment]
Hi there,

Do you have any updates on this?
Thanks!

**Comment by brandonmwest** [comment]
Might be this easy to make the tests pass.        

        private static readonly JsonSerializerSettings _settings = new JsonSerializerSettings
        {
            StringEscapeHandling = StringEscapeHandling.EscapeNonAscii,
            NullValueHandling = NullValueHandling.Ignore
        };

**Comment by brandonmwest** [comment]
I'm going to close this and solve the encoding issue with our current serializer. We should definitely refactor to JSON.NET soon but we should rethink how we structure the header settings. For example, this library [SendGridSharp](https://github.com/shibayan/SendGridSharp/blob/master/SendGridSharp/SmtpHeader.cs) has a much cleaner implementation.

**Comment by Sellathuraivelu** [comment]
HI Brandonmwest,
Do you have any updates on "non-ASCII characters with SMTPAPI headers under C#".Still we are not able to use sendgrid due to this issue.Please let us know if you have any updates on it.
Thanks,
Sella

**Comment by brandonmwest** [comment]
It is fixed in 5.1.0

**Comment by Sellathuraivelu** [comment]
Hi  Brandonmwest,
Thanks for your valuable reply .Can  you give some more details on 5.1.0? It will be helpful for us to move further.How can I use the version 5.1.0 to fix our non-ASCII characters issue in template engine.
Thanks,
Sella

**Comment by brandonmwest** [comment]
Sorry, I meant 1.2.0. The latest version of this library. If you use that, all header libraries will be escaped properly and will work. If you want to make it easier to specify a template engine template id, you can look at using https://github.com/sendgrid/sendgrid-csharp

**Comment by Sellathuraivelu** [comment]
Thanks a lot Brandonmwest .It is working fine now.

**Pull request closed without merging**
