### PR TITLE
Added Newtonsoft.Json as a package dependency in the nuspec file.

### PR DESCRIPTION
**Pull request by webster354**
Newtonsoft.Json version 10.0.0 (minimum version) is set as package dependency in the nuspec file.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/smtpapi-csharp?pullRequest=28) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/smtpapi-csharp?pullRequest=28) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: kevin.wong<br/>:x: webster354<br/><hr/>**kevin.wong** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/smtpapi-csharp?pullRequest=28) it.</sub>

**Comment by thinkingserious** [comment]
Hi @webster354,

Thanks for the PR!

I don't think we strictly need v10 for this library. How about a [version range](https://docs.microsoft.com/en-us/nuget/create-packages/dependency-versions#version-ranges), say (,9.0]. Or even lower. My concern is that this will be an unnecessary breaking change.

Could you please provide some feedback as to why you feel a dependency to v10 is warranted? Thanks!

With Best Regards,

Elmer

**Comment by webster354** [comment]
No specific reason for v10, but I think v9.0 needs to be the minimum.

image

**Comment by thinkingserious** [comment]
Hello @webster354,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
