### PR TITLE
Adds UseCase folder and README.md file

### LINKED ISSUE #67: Create a Use Cases Directory
Due to the success we have seen from hacktoberfest, we are seeing more people create use cases. This is amazing! 
We want to make sure that everyone can find them. Please help us to break up this file and make it easier to read and manage:
- Create a Use Cases Directory
- Put a README.md in this directory
- Make a file in the new directory for each individual Use Case from USE_CASES.md, copy the content to this file
- For each file you've created, link to it from the README you created
- Organize the links in the README by type
- Make sure the names of the files you created are related to the Use Case
Thank you!

### PR DESCRIPTION
**Pull request by Gimly**
In order to simplify the management of the use cases, it was asked to create a folder that will contain all the use cases.

Fixes #67

# Fixes # 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Adds the folder UseCases
- Adds a README.md that would contain the table of contents for the use cases (empty for now).

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/smtpapi-csharp?pullRequest=76) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/smtpapi-csharp?pullRequest=76) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/smtpapi-csharp?pullRequest=76) it.</sub>

**Comment by thinkingserious** [comment]
Hello @Gimly!

Thanks for the PR! Could you please [sign the CLA](
https://cla.sendgrid.com/sendgrid/smtpapi-csharp?pullRequest=76) for this rep so we can merge it? Thanks!

With Best Regards,

Elmer

**Comment by Gimly** [comment]
@thinkingserious done, you're welcome

**Comment by thinkingserious** [comment]
Hello @Gimly,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
