### PR TITLE
Move to netstandard1.0 and examples and tests to netcoreapp2.0

### PR DESCRIPTION
**Pull request by ViktorHofer**
Fixes https://github.com/sendgrid/smtpapi-csharp/issues/71

- move to netstandard1.0:
- cross platform support (Unix, OSX)
- switch to new csproj format and remove nuspec files
- switch tests and examples to run on netcoreapp

Nuget Package can be directly built via Visual Studio or via `dotnet pack`.

cc @danmosemsft

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/smtpapi-csharp?pullRequest=72) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/smtpapi-csharp?pullRequest=72) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/smtpapi-csharp?pullRequest=72) it.</sub>

**Comment by danmosemsft** [comment]
cc @weshaggard

**Comment by ViktorHofer** [comment]
Sendgrid team, I now waited couple of months but no reaction from your side. At least comment on the PR, otherwise I will just close it.

**Comment by smileyiori** [comment]
Hello,
This PR has been approved?

**Comment by ViktorHofer** [comment]
No progress for a year now. Hilarious

**Pull request closed without merging**
